import json

notebook = {
    'metadata': {
        'kernelspec': {'language': 'python', 'display_name': 'Python 3', 'name': 'python3'},
        'language_info': {'name': 'python'}
    },
    'nbformat_minor': 4,
    'nbformat': 4,
    'cells': [
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                '# Programmatic offline installation of zarr using the attached wheels dataset\n',
                'import sys\n',
                'import subprocess\n',
                'import importlib\n',
                '\n',
                'print("Installing dependencies offline...")\n',
                'subprocess.run([\n',
                '    sys.executable, "-m", "pip", "install",\n',
                '    "--no-index",\n',
                '    "--find-links=/kaggle/input/zarr-offline-wheels",\n',
                '    "zarr",\n',
                '    "-q"\n',
                '])\n',
                'importlib.invalidate_caches()\n',
                'print("Dependencies installed offline successfully.")\n'
            ]
        },
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                'import numpy as np\n',
                'import pandas as pd\n',
                'import os\n',
                'import zarr\n',
                'import networkx as nx\n',
                'from scipy.ndimage import gaussian_filter\n',
                'from skimage.feature import peak_local_max\n',
                'from scipy.optimize import linear_sum_assignment\n',
                'print("All libraries imported successfully.")\n'
            ]
        },
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                '# Debug: List all directories and files in /kaggle/input to find the correct data paths\n',
                'print("Listing /kaggle/input structure:")\n',
                'if os.path.exists("/kaggle/input"):\n',
                '    for root, dirs, files in os.walk("/kaggle/input"):\n',
                '        print(f"Root: {root} | Dirs: {dirs} | Files: {files[:5]}")\n',
                'else:\n',
                '    print("/kaggle/input does not exist.")\n'
            ]
        },
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                'def detect_cells_3d(image, voxel_scale=(1.625, 0.40625, 0.40625), cell_radius_um=3.0, min_dist_um=1.5):\n',
                '    sz, sy, sx = voxel_scale\n',
                '    \n',
                '    # Normalize image to [0, 1] range to make threshold invariant to bit-depth\n',
                '    img_min = np.min(image)\n',
                '    img_max = np.max(image)\n',
                '    denom = img_max - img_min\n',
                '    if denom < 1e-5:\n',
                '        denom = 1.0\n',
                '    img_norm = (image - img_min) / denom\n',
                '    \n',
                '    # Compute anisotropic sigmas directly on voxel coordinates\n',
                '    sigma_low = (cell_radius_um * 0.5 / sz, cell_radius_um * 0.5 / sy, cell_radius_um * 0.5 / sx)\n',
                '    sigma_high = (cell_radius_um * 1.0 / sz, cell_radius_um * 1.0 / sy, cell_radius_um * 1.0 / sx)\n',
                '    \n',
                '    # Run Gaussian filters directly on normalized image\n',
                '    img_smooth_low = gaussian_filter(img_norm, sigma=sigma_low)\n',
                '    img_smooth_high = gaussian_filter(img_norm, sigma=sigma_high)\n',
                '    dog = img_smooth_low - img_smooth_high\n',
                '    \n',
                '    # Robust dynamic threshold based on 99th percentile of positive DoG values\n',
                '    pos_dog = dog[dog > 0]\n',
                '    ref_val = np.percentile(pos_dog, 99) if len(pos_dog) > 0 else 1e-3\n',
                '    threshold_abs = max(0.005, 0.20 * ref_val)\n',
                '    \n',
                '    # Extract all local peaks in voxel units (minimum distance of 1 voxel)\n',
                '    peaks = peak_local_max(dog, min_distance=1, threshold_abs=threshold_abs, exclude_border=False)\n',
                '    if len(peaks) == 0:\n',
                '        return []\n',
                '        \n',
                '    # Convert peaks to physical coordinates (micrometers)\n',
                '    peaks_physical = []\n',
                '    for p in peaks:\n',
                '        pz, py, px = p\n',
                '        peaks_physical.append((pz * sz, py * sy, px * sx, pz, py, px))\n',
                '        \n',
                '    # Sort peaks by intensity of the DoG response\n',
                '    intensities = [dog[p[3], p[4], p[5]] for p in peaks_physical]\n',
                '    sorted_idx = np.argsort(intensities)[::-1]\n',
                '    \n',
                '    # Perform Non-Maximum Suppression (NMS) in physical space\n',
                '    keep = []\n',
                '    keep_coords_physical = []\n',
                '    \n',
                '    for idx in sorted_idx:\n',
                '        p = peaks_physical[idx]\n',
                '        p_phys = np.array([p[0], p[1], p[2]])\n',
                '        \n',
                '        too_close = False\n',
                '        for k_phys in keep_coords_physical:\n',
                '            dist = np.sqrt(np.sum((p_phys - k_phys) ** 2))\n',
                '            if dist < min_dist_um:\n',
                '                too_close = True\n',
                '                break\n',
                '                \n',
                '        if not too_close:\n',
                '            keep.append((int(p[3]), int(p[4]), int(p[5])))\n',
                '            keep_coords_physical.append(p_phys)\n',
                '            \n',
                '    return keep\n'
            ]
        },
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                'def link_cells(detections_by_time, voxel_scale=(1.625, 0.40625, 0.40625), max_dist_um=6.0, div_max_dist_um=5.0, max_sibling_dist_um=5.0, max_gap_dist_um=4.0):\n',
                '    sz, sy, sx = voxel_scale\n',
                '    nodes_list = []\n',
                '    node_id_map = {}\n',
                '    next_node_id = 1\n',
                '    T = max(detections_by_time.keys()) + 1 if detections_by_time else 0\n',
                '    for t in range(T):\n',
                '        t_detections = detections_by_time.get(t, [])\n',
                '        for idx, (z, y, x) in enumerate(t_detections):\n',
                '            node_id = next_node_id\n',
                '            next_node_id += 1\n',
                '            node_id_map[(t, idx)] = node_id\n',
                '            nodes_list.append({\'node_id\': node_id, \'t\': t, \'z\': int(z), \'y\': int(y), \'x\': int(x)})\n',
                '    nodes_df = pd.DataFrame(nodes_list)\n',
                '    edges_list = []\n',
                '    for t in range(T - 1):\n',
                '        dets_t = detections_by_time.get(t, [])\n',
                '        dets_t1 = detections_by_time.get(t + 1, [])\n',
                '        if not dets_t or not dets_t1:\n',
                '            continue\n',
                '        arr_t = np.array(dets_t, dtype=np.float32)\n',
                '        arr_t1 = np.array(dets_t1, dtype=np.float32)\n',
                '        diff = arr_t[:, None, :] - arr_t1[None, :, :]\n',
                '        diff[:, :, 0] *= sz\n',
                '        diff[:, :, 1] *= sy\n',
                '        diff[:, :, 2] *= sx\n',
                '        dist_matrix = np.sqrt(np.sum(diff ** 2, axis=-1))\n',
                '        cost_matrix = dist_matrix.copy()\n',
                '        cost_matrix[cost_matrix > max_dist_um] = 1e9\n',
                '        row_ind, col_ind = linear_sum_assignment(cost_matrix)\n',
                '        matched_t1 = set()\n',
                '        parent_to_children = {i: [] for i in range(len(dets_t))}\n',
                '        parent_child_links = []\n',
                '        for r, c in zip(row_ind, col_ind):\n',
                '            if dist_matrix[r, c] <= max_dist_um:\n',
                '                parent_id = node_id_map[(t, r)]\n',
                '                child_id = node_id_map[(t + 1, c)]\n',
                '                parent_child_links.append((parent_id, child_id))\n',
                '                matched_t1.add(c)\n',
                '                parent_to_children[r].append(c)\n',
                '        unmatched_t1 = [c for c in range(len(dets_t1)) if c not in matched_t1]\n',
                '        for c in unmatched_t1:\n',
                '            parent_dists = dist_matrix[:, c]\n',
                '            best_r = np.argmin(parent_dists)\n',
                '            if parent_dists[best_r] <= div_max_dist_um:\n',
                '                existing_children = parent_to_children[best_r]\n',
                '                if len(existing_children) == 1:\n',
                '                    sibling_idx = existing_children[0]\n',
                '                    sib_diff = arr_t1[sibling_idx] - arr_t1[c]\n',
                '                    sib_dist = np.sqrt((sib_diff[0]*sz)**2 + (sib_diff[1]*sy)**2 + (sib_diff[2]*sx)**2)\n',
                '                    if sib_dist <= max_sibling_dist_um:\n',
                '                        parent_id = node_id_map[(t, best_r)]\n',
                '                        child_id = node_id_map[(t + 1, c)]\n',
                '                        parent_child_links.append((parent_id, child_id))\n',
                '                        parent_to_children[best_r].append(c)\n',
                '        for parent_id, child_id in parent_child_links:\n',
                '            edges_list.append({\'source_id\': parent_id, \'target_id\': child_id})\n',
                '    G = nx.DiGraph()\n',
                '    for _, node in nodes_df.iterrows():\n',
                '        G.add_node(int(node[\'node_id\']), t=int(node[\'t\']), z=node[\'z\'], y=node[\'y\'], x=node[\'x\'])\n',
                '    for edge in edges_list:\n',
                '        G.add_edge(int(edge[\'source_id\']), int(edge[\'target_id\']))\n',
                '    terminating = [n for n in G.nodes() if G.out_degree(n) == 0 and G.nodes[n][\'t\'] < T - 1]\n',
                '    initiating = [n for n in G.nodes() if G.in_degree(n) == 0 and G.nodes[n][\'t\'] > 0]\n',
                '    added_nodes = []\n',
                '    added_edges = []\n',
                '    matched_initiating = set()\n',
                '    for u in terminating:\n',
                '        t_u = G.nodes[u][\'t\']\n',
                '        u_coords = np.array([G.nodes[u][\'z\'] * sz, G.nodes[u][\'y\'] * sy, G.nodes[u][\'x\'] * sx])\n',
                '        best_v = None\n',
                '        best_dist = 1e9\n',
                '        candidates = [v for v in initiating if G.nodes[v][\'t\'] == t_u + 2 and v not in matched_initiating]\n',
                '        for v in candidates:\n',
                '            v_coords = np.array([G.nodes[v][\'z\'] * sz, G.nodes[v][\'y\'] * sy, G.nodes[v][\'x\'] * sx])\n',
                '            dist = np.sqrt(np.sum((u_coords - v_coords) ** 2))\n',
                '            if dist <= max_gap_dist_um and dist < best_dist:\n',
                '                best_dist = dist\n',
                '                best_v = v\n',
                '        if best_v is not None:\n',
                '            matched_initiating.add(best_v)\n',
                '            interp_z = int(round((G.nodes[u][\'z\'] + G.nodes[best_v][\'z\']) / 2))\n',
                '            interp_y = int(round((G.nodes[u][\'y\'] + G.nodes[best_v][\'y\']) / 2))\n',
                '            interp_x = int(round((G.nodes[u][\'x\'] + G.nodes[best_v][\'x\']) / 2))\n',
                '            interp_id = next_node_id\n',
                '            next_node_id += 1\n',
                '            added_nodes.append({\'node_id\': interp_id, \'t\': t_u + 1, \'z\': interp_z, \'y\': interp_y, \'x\': interp_x})\n',
                '            added_edges.append({\'source_id\': u, \'target_id\': interp_id})\n',
                '            added_edges.append({\'source_id\': interp_id, \'target_id\': best_v})\n',
                '    if added_nodes:\n',
                '        nodes_df = pd.concat([nodes_df, pd.DataFrame(added_nodes)], ignore_index=True)\n',
                '    edges_df = pd.DataFrame(edges_list + added_edges) if (edges_list or added_edges) else pd.DataFrame(columns=[\'source_id\', \'target_id\'])\n',
                '    return nodes_df, edges_df\n'
            ]
        },
        {
            'cell_type': 'code',
            'metadata': {},
            'outputs': [],
            'execution_count': None,
            'source': [
                'import gc\n',
                '# Dynamically resolve the test directory path by walking the input directory\n',
                'test_dir = None\n',
                'for root, dirs, files in os.walk("/kaggle/input"):\n',
                '    if "test" in dirs:\n',
                '        test_dir = os.path.join(root, "test")\n',
                '        break\n',
                '    elif "test" in root.split(os.sep):\n',
                '        # Already inside a test folder\n',
                '        test_dir = root\n',
                '        break\n',
                '\n',
                'if test_dir is None:\n',
                '    # Fallback to standard path\n',
                '    test_dir = \'/kaggle/input/biohub-cell-tracking-during-development/test\'\n',
                '\n',
                'print(f"Resolved test directory path: {test_dir}")\n',
                'submission_rows = []\n',
                'if os.path.exists(test_dir):\n',
                '    print("Processing real test dataset...")\n',
                '    # Strictly filter for files/folders ending in .zarr to avoid processing system files/wheels\n',
                '    zarr_files = [f for f in os.listdir(test_dir) if f.endswith(\'.zarr\')]\n',
                '    print(f"Found test files: {zarr_files}")\n',
                '    \n',
                '    for zarr_name in zarr_files:\n',
                '        zarr_path = os.path.join(test_dir, zarr_name)\n',
                '        dataset_name = zarr_name.replace(\'.zarr\', \'\')\n',
                '        print(f"Processing dataset {dataset_name}...")\n',
                '        \n',
                '        try:\n',
                '            try:\n',
                '                z = zarr.open(zarr_path, mode=\'r\')\n',
                '                arr = z[\'0\'] if \'0\' in z else z\n',
                '            except Exception:\n',
                '                arr = zarr.open(os.path.join(zarr_path, \'0\'), mode=\'r\')\n',
                '            \n',
                '            T = arr.shape[0]\n',
                '            detected_centroids = {}\n',
                '            for t in range(T):\n',
                '                frame = arr[t]\n',
                '                centroids = detect_cells_3d(frame, cell_radius_um=3.0, min_dist_um=1.5)\n',
                '                detected_centroids[t] = centroids\n',
                '            pred_nodes, pred_edges = link_cells(detected_centroids, max_dist_um=6.0, div_max_dist_um=5.0, max_sibling_dist_um=5.0, max_gap_dist_um=4.0)\n',
                '            \n',
                '            # If no cells were detected, insert a dummy node to ensure dataset completeness\n',
                '            if len(pred_nodes) == 0:\n',
                '                print(f"Warning: No cells detected for {dataset_name}. Generating dummy node.")\n',
                '                pred_nodes = pd.DataFrame([{\n',
                '                    \'node_id\': 1, \'t\': 0, \'z\': 32, \'y\': 128, \'x\': 128\n',
                '                }])\n',
                '                pred_edges = pd.DataFrame(columns=[\'source_id\', \'target_id\'])\n',
                '                \n',
                '        except Exception as e:\n',
                '            print(f"Error processing dataset {dataset_name}: {e}. Creating fallback dummy node.")\n',
                '            pred_nodes = pd.DataFrame([{\n',
                '                \'node_id\': 1, \'t\': 0, \'z\': 32, \'y\': 128, \'x\': 128\n',
                '            }])\n',
                '            pred_edges = pd.DataFrame(columns=[\'source_id\', \'target_id\'])\n',
                '            \n',
                '        # Append records for this dataset\n',
                '        for _, node in pred_nodes.iterrows():\n',
                '            submission_rows.append({\n',
                '                \'dataset\': dataset_name,\n',
                '                \'row_type\': \'node\',\n',
                '                \'node_id\': int(node[\'node_id\']),\n',
                '                \'t\': int(node[\'t\']),\n',
                '                \'z\': int(node[\'z\']),\n',
                '                \'y\': int(node[\'y\']),\n',
                '                \'x\': int(node[\'x\']),\n',
                '                \'source_id\': -1,\n',
                '                \'target_id\': -1\n',
                '            })\n',
                '        for _, edge in pred_edges.iterrows():\n',
                '            submission_rows.append({\n',
                '                \'dataset\': dataset_name,\n',
                '                \'row_type\': \'edge\',\n',
                '                \'node_id\': -1,\n',
                '                \'t\': -1,\n',
                '                \'z\': -1,\n',
                '                \'y\': -1,\n',
                '                \'x\': -1,\n',
                '                \'source_id\': int(edge[\'source_id\']),\n',
                '                \'target_id\': int(edge[\'target_id\'])\n',
                '            })\n',
                '            \n',
                '        del detected_centroids, pred_nodes, pred_edges, arr, z\n',
                '        gc.collect()\n',
                'else:\n',
                '    print("Test directory not found.")\n',
                '\n',
                '# Construct the final DataFrame with strict type checks\n',
                'if submission_rows:\n',
                '    submission_df = pd.DataFrame(submission_rows)\n',
                '    # Force all ID and coordinate columns to be standard integers\n',
                '    for col in [\'node_id\', \'t\', \'z\', \'y\', \'x\', \'source_id\', \'target_id\']:\n',
                '        submission_df[col] = submission_df[col].astype(np.int64)\n',
                '    submission_df.insert(0, \'id\', np.arange(len(submission_df)).astype(np.int64))\n',
                'else:\n',
                '    # If empty, write empty DataFrame with correct headers to prevent submission crashes\n',
                '    submission_df = pd.DataFrame(columns=[\'id\', \'dataset\', \'row_type\', \'node_id\', \'t\', \'z\', \'y\', \'x\', \'source_id\', \'target_id\'])\n',
                '\n',
                '# Reindex to guarantee exact column ordering\n',
                'cols = [\'id\', \'dataset\', \'row_type\', \'node_id\', \'t\', \'z\', \'y\', \'x\', \'source_id\', \'target_id\']\n',
                'submission_df = submission_df[cols]\n',
                'submission_df.to_csv(\'submission.csv\', index=False)\n',
                'print(f"Generated submission.csv with {len(submission_df)} rows.")\n'
            ]
        }
    ]
}

with open('temp_kernel/biohub-3d-cell-tracking-development.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print('Notebook generated successfully.')
